export enum EstatesReducers {
  GET_ALL_ESTATES_SUCCESS = 'GET_ALL_ESTATES_SUCCESS',
  GET_ALL_ESTATES_REQUEST = 'GET_ALL_ESTATES_REQUEST',
  GET_ALL_ESTATES_ERROR = 'GET_ALL_ESTATES_ERROR',
  ESTATES_IDLE = 'ESTATES_IDLE',
}
